# Generated by Django 6.0.3 on 2026-04-03 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_quizresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_score', models.IntegerField(default=10)),
                ('participation_score', models.IntegerField(default=10)),
                ('understanding_score', models.IntegerField(default=10)),
                ('comments', models.TextField()),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.session')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
