# Generated by Django 6.0.3 on 2026-04-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_trainerfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='check_in_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
