# Generated by Django 6.0.3 on 2026-04-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_attendance_check_in_time_attendance_check_out_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresult',
            name='total_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('TRAINER', 'Trainer'), ('TRAINEE', 'Trainee'), ('CLIENT', 'Client')], default='TRAINEE', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='quizresult',
            unique_together={('quiz', 'trainee')},
        ),
    ]
