# Generated by Django 5.2.14 on 2026-05-14 11:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_quizresult_total_score_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quizresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TRAINER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_hours',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='course',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='content_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_mandatory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='overall_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='feedback',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='trainer_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='feedback',
            name='venue_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='passing_score',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit_minutes',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='attempt_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.session'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='time_taken_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='enrollment_link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='session',
            name='max_trainees',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='session',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AddField(
            model_name='session',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='session',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=15),
        ),
        migrations.AddField(
            model_name='trainerfeedback',
            name='aptitude_score',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='trainerfeedback',
            name='discipline_score',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='trainerfeedback',
            name='overall_score',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='trainerfeedback',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined_org',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='managed_site',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='user',
            name='site_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late')], default='ABSENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=10),
        ),
        migrations.AlterField(
            model_name='session',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='trainer',
            field=models.ForeignKey(limit_choices_to={'role': 'TRAINER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainerfeedback',
            name='attendance_score',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='trainerfeedback',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trainerfeedback',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainerfeedback',
            name='participation_score',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='trainerfeedback',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainerfeedback',
            name='understanding_score',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('is_valid', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.course')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.session')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SiteLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(blank=True, limit_choices_to={'role': 'CLIENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_locations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='site_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='api.sitelocation'),
        ),
    ]
