# Generated by Django 5.2.14 on 2026-05-15 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_improvements_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='enrolled_via',
            field=models.CharField(
                choices=[('QR', 'QR Scan'), ('LINK', 'Direct Link'), ('MANUAL', 'Manual'), ('SELF', 'Self')],
                default='MANUAL',
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TRAINER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='traineesessionprogress',
            name='trainee',
            field=models.ForeignKey(limit_choices_to={'role': 'TRAINEE'}, on_delete=django.db.models.deletion.CASCADE, related_name='session_progress', to=settings.AUTH_USER_MODEL),
        ),
    ]
